export enum AppSignal {
  SHOW_POPUP_WIN = 'SHOW_POPUP_WIN',
  SHOW_POPUP_LOSE = 'SHOW_POPUP_LOSE',
  HIDE_POPUPS = 'HIDE_POPUPS',
  TILE_CLICKED = 'TILE_CLICKED',

  BOOSTER_TELEPORT_CLICKED = 'BOOSTER_TELEPORT_CLICKED',
  BOOSTER_BOMB_CLICKED = 'BOOSTER_BOMB_CLICKED',

  NO_MOVES_OK_CLICKED = 'NO_MOVES_OK_CLICKED',

  MEGA_BOMB_EXPLODED = 'MEGA_BOMB_EXPLODED',
}
